name: Publish (.NET Library)

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release -v normal -p:Version=${{ github.event.release.tag_name }} AppServiceSharp/AppServiceSharp.csproj

      - name: Pack (Beta)
        run: dotnet pack -c Release --no-build -o ./packages -p:PackageVersion=${{ github.event.release.tag_name }}-beta AppServiceSharp/AppServiceSharp.csproj
        if: "github.event.release.prerelease"

      - name: Pack (Stable)
        run: dotnet pack -c Release --no-build -o ./packages -p:PackageVersion=${{ github.event.release.tag_name }} AppServiceSharp/AppServiceSharp.csproj
        if: "!github.event.release.prerelease"

      - name: Publish
        run: dotnet nuget push -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NUGET_KEY }} ./packages/*.nupkg